# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5972d6dbb3991def8677267d72dc779bf45c038ae2da9f6f13dfcce378359cc5871b98a7d6c1ccb4a194ea21922084c6371113f8c6541c039bc1e746e88f6b3

test:
  secret_key_base: 3a7ed04d1b5961ac128f3b865aa1ad5f474763c2e3a99c70b0eddc5aab537ccf07ee33fe5116d79d68ba341e4ee5a4643dec5299b1160d32ff544906110e425b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
